import './globals.scss';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { ReactNode } from 'react';
import { getUserBySessionToken } from '../database/users';
import styles from './layout.module.scss';
import { LogoutButton } from './logoutbutton';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};

export default async function RootLayout({ children }: Props) {
  // 1. get the session token from the cookie
  const cookieStore = cookies();
  const sessionToken = cookieStore.get('sessionToken');

  const user = !sessionToken?.value
    ? undefined
    : await getUserBySessionToken(sessionToken.value);
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className={styles.navbar}>
          <div>
            <Link href="http://localhost:3000">Home</Link>
            <Link href="http://localhost:3000/knights">Knights</Link>
            <Link href="http://localhost:3000/samurai">Samurai</Link>
            <Link href="http://localhost:3000/vikings">Vikings</Link>
            <Link href="http://localhost:3000/customise">Customise</Link>
          </div>
          <div>
            {user ? (
              <>
                <LogoutButton />
                <Link href={`http://localhost:3000/profile/${user.username}`}>
                  Profile
                </Link>
                <Link
                  href={`http://localhost:3000/uploadfotos/${user.username}`}
                >
                  upload
                </Link>
              </>
            ) : (
              <>
                <Link href="http://localhost:3000/register">register</Link>
                <Link href="http://localhost:3000/login">login</Link>
              </>
            )}
          </div>
        </nav>

        {children}
        <footer>
          <div className={styles.footer}>
            <Link href="/">Contact us</Link>
            <Link href="/">Privacy Policy</Link>
            <Link href="/">Terms&Conditions</Link>
            <Link href="/">Our Services</Link>
          </div>

          <div className={styles.copyright}>
            Dunmaglass Copyright © 2023 Dunmaglass - All rights reserved ||
            Designed By: Raphael
          </div>
        </footer>
      </body>
    </html>
  );
}
